export const HEADINGS = {
  HERO: "Hero Section",
  INTRODUCTION: "Introduction",
  LEARNING_OBJECTIVES: "Learning Objectives",
  PREREQUISITES: "Prerequisites",
  HISTORY: "History",
  WHY_IMPORTANT: "Why is it Important?",
  CORE_COMPONENTS: "Core Components",
  HOW_IT_WORKS: "How It Works",
  WORKFLOW: "Step-by-Step Workflow",
  REAL_WORLD_EXAMPLE: "Real World Example",
  APPLICATIONS: "Applications",
  ADVANTAGES: "Advantages",
  LIMITATIONS: "Limitations",
  CURRENT_RESEARCH: "Current Research Challenges",
  BEST_PRACTICES: "Best Practices",
  COMMON_MISTAKES: "Common Mistakes",
  INTERVIEW: "Interview Questions",
  SUMMARY: "Summary",
  GLOSSARY: "Glossary",
  QUIZ: "Quiz",
  REFERENCES: "References",
  NEXT_CONCEPT: "Next Concept",
};